/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StreamlineContainer {
        "visible": boolean;
    }
    interface StreamlineDropdown {
        "items": any[];
        "type": string;
    }
    interface StreamlineSearch {
    }
}
declare global {
    interface HTMLStreamlineContainerElement extends Components.StreamlineContainer, HTMLStencilElement {
    }
    var HTMLStreamlineContainerElement: {
        prototype: HTMLStreamlineContainerElement;
        new (): HTMLStreamlineContainerElement;
    };
    interface HTMLStreamlineDropdownElement extends Components.StreamlineDropdown, HTMLStencilElement {
    }
    var HTMLStreamlineDropdownElement: {
        prototype: HTMLStreamlineDropdownElement;
        new (): HTMLStreamlineDropdownElement;
    };
    interface HTMLStreamlineSearchElement extends Components.StreamlineSearch, HTMLStencilElement {
    }
    var HTMLStreamlineSearchElement: {
        prototype: HTMLStreamlineSearchElement;
        new (): HTMLStreamlineSearchElement;
    };
    interface HTMLElementTagNameMap {
        "streamline-container": HTMLStreamlineContainerElement;
        "streamline-dropdown": HTMLStreamlineDropdownElement;
        "streamline-search": HTMLStreamlineSearchElement;
    }
}
declare namespace LocalJSX {
    interface StreamlineContainer {
        "visible"?: boolean;
    }
    interface StreamlineDropdown {
        "items"?: any[];
        "type"?: string;
    }
    interface StreamlineSearch {
    }
    interface IntrinsicElements {
        "streamline-container": StreamlineContainer;
        "streamline-dropdown": StreamlineDropdown;
        "streamline-search": StreamlineSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "streamline-container": LocalJSX.StreamlineContainer & JSXBase.HTMLAttributes<HTMLStreamlineContainerElement>;
            "streamline-dropdown": LocalJSX.StreamlineDropdown & JSXBase.HTMLAttributes<HTMLStreamlineDropdownElement>;
            "streamline-search": LocalJSX.StreamlineSearch & JSXBase.HTMLAttributes<HTMLStreamlineSearchElement>;
        }
    }
}
