/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StreamlineContainer {
    }
}
declare global {
    interface HTMLStreamlineContainerElement extends Components.StreamlineContainer, HTMLStencilElement {
    }
    var HTMLStreamlineContainerElement: {
        prototype: HTMLStreamlineContainerElement;
        new (): HTMLStreamlineContainerElement;
    };
    interface HTMLElementTagNameMap {
        "streamline-container": HTMLStreamlineContainerElement;
    }
}
declare namespace LocalJSX {
    interface StreamlineContainer {
    }
    interface IntrinsicElements {
        "streamline-container": StreamlineContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "streamline-container": LocalJSX.StreamlineContainer & JSXBase.HTMLAttributes<HTMLStreamlineContainerElement>;
        }
    }
}
