/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StreamlineBottomBar {
    }
    interface StreamlineContainer {
        "network": false;
        "setState": (data: any) => Promise<unknown>;
        "test": false;
        "visible": false;
    }
    interface StreamlineDropdown {
        "items": any[];
        "type": string;
    }
    interface StreamlineEntries {
    }
    interface StreamlineHeader {
        "item": { ID: number; adminUrl: string; guid: string; href: string; hrefEdit: string; isMultisite: boolean; name: string; path: string; post_title: string; route: string; siteId: number; tab: string; title: string; type: string; };
        "mb": any;
    }
    interface StreamlineRow {
        "isFav": boolean;
        "item": { ID: number; adminUrl: string; guid: string; href: string; hrefEdit: string; name: string; path: string; post_title: string; route: string; siteId: number; tab: string; type: string; };
        "mb": any;
        "table": any;
    }
    interface StreamlineRows {
    }
    interface StreamlineSearch {
    }
    interface StreamlineSettings {
    }
}
declare global {
    interface HTMLStreamlineBottomBarElement extends Components.StreamlineBottomBar, HTMLStencilElement {
    }
    var HTMLStreamlineBottomBarElement: {
        prototype: HTMLStreamlineBottomBarElement;
        new (): HTMLStreamlineBottomBarElement;
    };
    interface HTMLStreamlineContainerElement extends Components.StreamlineContainer, HTMLStencilElement {
    }
    var HTMLStreamlineContainerElement: {
        prototype: HTMLStreamlineContainerElement;
        new (): HTMLStreamlineContainerElement;
    };
    interface HTMLStreamlineDropdownElement extends Components.StreamlineDropdown, HTMLStencilElement {
    }
    var HTMLStreamlineDropdownElement: {
        prototype: HTMLStreamlineDropdownElement;
        new (): HTMLStreamlineDropdownElement;
    };
    interface HTMLStreamlineEntriesElement extends Components.StreamlineEntries, HTMLStencilElement {
    }
    var HTMLStreamlineEntriesElement: {
        prototype: HTMLStreamlineEntriesElement;
        new (): HTMLStreamlineEntriesElement;
    };
    interface HTMLStreamlineHeaderElement extends Components.StreamlineHeader, HTMLStencilElement {
    }
    var HTMLStreamlineHeaderElement: {
        prototype: HTMLStreamlineHeaderElement;
        new (): HTMLStreamlineHeaderElement;
    };
    interface HTMLStreamlineRowElement extends Components.StreamlineRow, HTMLStencilElement {
    }
    var HTMLStreamlineRowElement: {
        prototype: HTMLStreamlineRowElement;
        new (): HTMLStreamlineRowElement;
    };
    interface HTMLStreamlineRowsElement extends Components.StreamlineRows, HTMLStencilElement {
    }
    var HTMLStreamlineRowsElement: {
        prototype: HTMLStreamlineRowsElement;
        new (): HTMLStreamlineRowsElement;
    };
    interface HTMLStreamlineSearchElement extends Components.StreamlineSearch, HTMLStencilElement {
    }
    var HTMLStreamlineSearchElement: {
        prototype: HTMLStreamlineSearchElement;
        new (): HTMLStreamlineSearchElement;
    };
    interface HTMLStreamlineSettingsElement extends Components.StreamlineSettings, HTMLStencilElement {
    }
    var HTMLStreamlineSettingsElement: {
        prototype: HTMLStreamlineSettingsElement;
        new (): HTMLStreamlineSettingsElement;
    };
    interface HTMLElementTagNameMap {
        "streamline-bottom-bar": HTMLStreamlineBottomBarElement;
        "streamline-container": HTMLStreamlineContainerElement;
        "streamline-dropdown": HTMLStreamlineDropdownElement;
        "streamline-entries": HTMLStreamlineEntriesElement;
        "streamline-header": HTMLStreamlineHeaderElement;
        "streamline-row": HTMLStreamlineRowElement;
        "streamline-rows": HTMLStreamlineRowsElement;
        "streamline-search": HTMLStreamlineSearchElement;
        "streamline-settings": HTMLStreamlineSettingsElement;
    }
}
declare namespace LocalJSX {
    interface StreamlineBottomBar {
    }
    interface StreamlineContainer {
        "network"?: false;
        "test"?: false;
        "visible"?: false;
    }
    interface StreamlineDropdown {
        "items"?: any[];
        "type"?: string;
    }
    interface StreamlineEntries {
    }
    interface StreamlineHeader {
        "item"?: { ID: number; adminUrl: string; guid: string; href: string; hrefEdit: string; isMultisite: boolean; name: string; path: string; post_title: string; route: string; siteId: number; tab: string; title: string; type: string; };
        "mb"?: any;
    }
    interface StreamlineRow {
        "isFav"?: boolean;
        "item"?: { ID: number; adminUrl: string; guid: string; href: string; hrefEdit: string; name: string; path: string; post_title: string; route: string; siteId: number; tab: string; type: string; };
        "mb"?: any;
        "table"?: any;
    }
    interface StreamlineRows {
    }
    interface StreamlineSearch {
    }
    interface StreamlineSettings {
    }
    interface IntrinsicElements {
        "streamline-bottom-bar": StreamlineBottomBar;
        "streamline-container": StreamlineContainer;
        "streamline-dropdown": StreamlineDropdown;
        "streamline-entries": StreamlineEntries;
        "streamline-header": StreamlineHeader;
        "streamline-row": StreamlineRow;
        "streamline-rows": StreamlineRows;
        "streamline-search": StreamlineSearch;
        "streamline-settings": StreamlineSettings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "streamline-bottom-bar": LocalJSX.StreamlineBottomBar & JSXBase.HTMLAttributes<HTMLStreamlineBottomBarElement>;
            "streamline-container": LocalJSX.StreamlineContainer & JSXBase.HTMLAttributes<HTMLStreamlineContainerElement>;
            "streamline-dropdown": LocalJSX.StreamlineDropdown & JSXBase.HTMLAttributes<HTMLStreamlineDropdownElement>;
            "streamline-entries": LocalJSX.StreamlineEntries & JSXBase.HTMLAttributes<HTMLStreamlineEntriesElement>;
            "streamline-header": LocalJSX.StreamlineHeader & JSXBase.HTMLAttributes<HTMLStreamlineHeaderElement>;
            "streamline-row": LocalJSX.StreamlineRow & JSXBase.HTMLAttributes<HTMLStreamlineRowElement>;
            "streamline-rows": LocalJSX.StreamlineRows & JSXBase.HTMLAttributes<HTMLStreamlineRowsElement>;
            "streamline-search": LocalJSX.StreamlineSearch & JSXBase.HTMLAttributes<HTMLStreamlineSearchElement>;
            "streamline-settings": LocalJSX.StreamlineSettings & JSXBase.HTMLAttributes<HTMLStreamlineSettingsElement>;
        }
    }
}
