/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StreamlineContainer {
        "mac": boolean;
        "setState": (data: any) => Promise<void>;
        "toggle": () => Promise<void>;
        "visible": boolean;
    }
    interface StreamlineEntries {
    }
    interface StreamlineSearch {
    }
    interface StreamlineSidebar {
    }
    interface StreamlineUiDrawer {
    }
    interface StreamlineUiDropdown {
        "items": any[];
        "type": string;
    }
    interface StreamlineUiInput {
        "handleInput": Function;
        "invalid": boolean;
        "label": string;
        "uid": string;
        "value": string;
    }
}
declare global {
    interface HTMLStreamlineContainerElement extends Components.StreamlineContainer, HTMLStencilElement {
    }
    var HTMLStreamlineContainerElement: {
        prototype: HTMLStreamlineContainerElement;
        new (): HTMLStreamlineContainerElement;
    };
    interface HTMLStreamlineEntriesElement extends Components.StreamlineEntries, HTMLStencilElement {
    }
    var HTMLStreamlineEntriesElement: {
        prototype: HTMLStreamlineEntriesElement;
        new (): HTMLStreamlineEntriesElement;
    };
    interface HTMLStreamlineSearchElement extends Components.StreamlineSearch, HTMLStencilElement {
    }
    var HTMLStreamlineSearchElement: {
        prototype: HTMLStreamlineSearchElement;
        new (): HTMLStreamlineSearchElement;
    };
    interface HTMLStreamlineSidebarElement extends Components.StreamlineSidebar, HTMLStencilElement {
    }
    var HTMLStreamlineSidebarElement: {
        prototype: HTMLStreamlineSidebarElement;
        new (): HTMLStreamlineSidebarElement;
    };
    interface HTMLStreamlineUiDrawerElement extends Components.StreamlineUiDrawer, HTMLStencilElement {
    }
    var HTMLStreamlineUiDrawerElement: {
        prototype: HTMLStreamlineUiDrawerElement;
        new (): HTMLStreamlineUiDrawerElement;
    };
    interface HTMLStreamlineUiDropdownElement extends Components.StreamlineUiDropdown, HTMLStencilElement {
    }
    var HTMLStreamlineUiDropdownElement: {
        prototype: HTMLStreamlineUiDropdownElement;
        new (): HTMLStreamlineUiDropdownElement;
    };
    interface HTMLStreamlineUiInputElement extends Components.StreamlineUiInput, HTMLStencilElement {
    }
    var HTMLStreamlineUiInputElement: {
        prototype: HTMLStreamlineUiInputElement;
        new (): HTMLStreamlineUiInputElement;
    };
    interface HTMLElementTagNameMap {
        "streamline-container": HTMLStreamlineContainerElement;
        "streamline-entries": HTMLStreamlineEntriesElement;
        "streamline-search": HTMLStreamlineSearchElement;
        "streamline-sidebar": HTMLStreamlineSidebarElement;
        "streamline-ui-drawer": HTMLStreamlineUiDrawerElement;
        "streamline-ui-dropdown": HTMLStreamlineUiDropdownElement;
        "streamline-ui-input": HTMLStreamlineUiInputElement;
    }
}
declare namespace LocalJSX {
    interface StreamlineContainer {
        "mac"?: boolean;
        "visible"?: boolean;
    }
    interface StreamlineEntries {
    }
    interface StreamlineSearch {
    }
    interface StreamlineSidebar {
    }
    interface StreamlineUiDrawer {
    }
    interface StreamlineUiDropdown {
        "items"?: any[];
        "type"?: string;
    }
    interface StreamlineUiInput {
        "handleInput"?: Function;
        "invalid"?: boolean;
        "label"?: string;
        "uid"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "streamline-container": StreamlineContainer;
        "streamline-entries": StreamlineEntries;
        "streamline-search": StreamlineSearch;
        "streamline-sidebar": StreamlineSidebar;
        "streamline-ui-drawer": StreamlineUiDrawer;
        "streamline-ui-dropdown": StreamlineUiDropdown;
        "streamline-ui-input": StreamlineUiInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "streamline-container": LocalJSX.StreamlineContainer & JSXBase.HTMLAttributes<HTMLStreamlineContainerElement>;
            "streamline-entries": LocalJSX.StreamlineEntries & JSXBase.HTMLAttributes<HTMLStreamlineEntriesElement>;
            "streamline-search": LocalJSX.StreamlineSearch & JSXBase.HTMLAttributes<HTMLStreamlineSearchElement>;
            "streamline-sidebar": LocalJSX.StreamlineSidebar & JSXBase.HTMLAttributes<HTMLStreamlineSidebarElement>;
            "streamline-ui-drawer": LocalJSX.StreamlineUiDrawer & JSXBase.HTMLAttributes<HTMLStreamlineUiDrawerElement>;
            "streamline-ui-dropdown": LocalJSX.StreamlineUiDropdown & JSXBase.HTMLAttributes<HTMLStreamlineUiDropdownElement>;
            "streamline-ui-input": LocalJSX.StreamlineUiInput & JSXBase.HTMLAttributes<HTMLStreamlineUiInputElement>;
        }
    }
}
