import { stateInternal } from '../store/internal';

export function setData() {
  const sites = [
    {
      index: 0,
      children: [
        {
          blog_id: '1',
          domain: 'fabrikat.local',
          path: '/',
          site_id: '1',
          registered: '2018-11-22 12:45:33',
          last_updated: '2021-09-29 10:12:15',
          public: '1',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '1',
          adminUrl: 'https://fabrikat.local/wp-admin/',
        },
        {
          blog_id: '294',
          domain: 'fabrikat.local',
          path: '/raum/',
          site_id: '1',
          registered: '2020-03-04 12:19:07',
          last_updated: '2020-06-16 22:11:32',
          public: '1',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '294',
          adminUrl: 'https://fabrikat.local/raum/wp-admin/',
        },
        {
          blog_id: '303',
          domain: 'fabrikat.local',
          path: '/spx/',
          site_id: '1',
          registered: '2020-04-23 19:55:30',
          last_updated: '2021-09-29 21:52:23',
          public: '1',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '303',
          adminUrl: 'https://fabrikat.local/spx/wp-admin/',
        },
        {
          blog_id: '305',
          domain: 'fabrikat.local',
          path: '/harmoni/',
          site_id: '1',
          registered: '2020-05-25 12:34:28',
          last_updated: '2021-02-16 01:11:31',
          public: '1',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '305',
          adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
        },
        {
          blog_id: '306',
          domain: 'fabrikat.local',
          path: '/spx-oxygen/',
          site_id: '1',
          registered: '2020-06-01 11:41:38',
          last_updated: '2021-09-29 20:31:53',
          public: '0',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '306',
          adminUrl: 'https://fabrikat.local/spx-oxygen/wp-admin/',
        },
        {
          blog_id: '309',
          domain: 'fabrikat.local',
          path: '/blockstudio/',
          site_id: '1',
          registered: '2020-09-28 18:02:14',
          last_updated: '2021-10-06 20:45:54',
          public: '1',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '309',
          adminUrl: 'https://fabrikat.local/blockstudio/wp-admin/',
        },
        {
          blog_id: '312',
          domain: 'fabrikat.local',
          path: '/dennis/',
          site_id: '1',
          registered: '2021-01-07 22:36:05',
          last_updated: '2021-01-07 23:29:53',
          public: '1',
          archived: '0',
          mature: '0',
          spam: '0',
          deleted: '0',
          lang_id: '0',
          siteId: '312',
          adminUrl: 'https://fabrikat.local/dennis/wp-admin/',
        },
      ],
      type: 'site',
    },
  ];
  stateInternal.entriesSite = sites;
  stateInternal.entriesSiteActive = sites;

  const fav = [
    {
      adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
      children: {
        Dashboard: {
          index: 0,
          name: 'Dashboard',
          children: {
            'index.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/index.php',
              index: 0,
              name: 'Home',
              nameParent: 'Dashboard',
              path: 'index.php',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Posts: {
          index: 1,
          name: 'Posts',
          children: {
            'post-new.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/post-new.php',
              index: 1,
              name: 'Add New',
              nameParent: 'Posts',
              path: 'post-new.php',
              siteId: 305,
              type: 'menu',
            },
            'edit.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php',
              index: 0,
              name: 'All Posts',
              nameParent: 'Posts',
              path: 'edit.php',
              siteId: 305,
              type: 'menu',
            },
          },
        },
      },
      siteId: 305,
      type: 'menu',
    },
    {
      adminUrl: 'https://fabrikat.local/spx/wp-admin/',
      children: {
        Downloads: {
          index: 4,
          name: 'Downloads',
          children: {
            'edit.php?post_type=download': {
              adminUrl: 'https://fabrikat.local/spx/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=download',
              index: 0,
              name: 'All Downloads',
              nameParent: 'Downloads',
              path: 'edit.php?post_type=download',
              siteId: 303,
              type: 'menu',
            },
            'edit.php?post_type=download&page=edd-tools': {
              adminUrl: 'https://fabrikat.local/spx/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=download&page=edd-tools',
              index: 9,
              name: 'Tools',
              nameParent: 'Downloads',
              path: 'edit.php?post_type=download&page=edd-tools',
              siteId: 303,
              type: 'menu',
            },
          },
        },
        Appearance: {
          index: 5,
          name: 'Appearance',
          children: {
            'customize.php?return=%2Fspx%2Fwp-admin%2F': {
              adminUrl: 'https://fabrikat.local/spx/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/customize.php?return=%2Fspx%2Fwp-admin%2F',
              index: 1,
              name: 'Customize',
              nameParent: 'Appearance',
              path: 'customize.php?return=%2Fspx%2Fwp-admin%2F',
              siteId: 303,
              type: 'menu',
            },
          },
        },
        Posts: {
          index: 1,
          name: 'Posts',
          children: {
            'edit.php': {
              adminUrl: 'https://fabrikat.local/spx/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php',
              index: 0,
              name: 'All Posts',
              nameParent: 'Posts',
              path: 'edit.php',
              siteId: 303,
              type: 'menu',
            },
            'edit-tags.php?taxonomy=category': {
              adminUrl: 'https://fabrikat.local/spx/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit-tags.php?taxonomy=category',
              index: 2,
              name: 'Categories',
              nameParent: 'Posts',
              path: 'edit-tags.php?taxonomy=category',
              siteId: 303,
              type: 'menu',
            },
          },
        },
        Media: {
          index: 2,
          name: 'Media',
          children: {
            'upload.php': {
              adminUrl: 'https://fabrikat.local/spx/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/upload.php',
              index: 0,
              name: 'Library',
              nameParent: 'Media',
              path: 'upload.php',
              siteId: 303,
              type: 'menu',
            },
          },
        },
      },
      siteId: 303,
      type: 'menu',
    },
    {
      adminUrl: 'https://fabrikat.local/blockstudio/wp-admin/',
      children: {
        Downloads: {
          index: 4,
          name: 'Downloads',
          children: {
            'edit.php?post_type=download': {
              adminUrl: 'https://fabrikat.local/blockstudio/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=download',
              index: 0,
              name: 'All Downloads',
              nameParent: 'Downloads',
              path: 'edit.php?post_type=download',
              siteId: 309,
              type: 'menu',
            },
            'post-new.php?post_type=download': {
              adminUrl: 'https://fabrikat.local/blockstudio/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/post-new.php?post_type=download',
              index: 1,
              name: 'Add New',
              nameParent: 'Downloads',
              path: 'post-new.php?post_type=download',
              siteId: 309,
              type: 'menu',
            },
          },
        },
      },
      siteId: 309,
      type: 'menu',
    },
    {
      adminUrl: 'https://fabrikat.local/dennis/wp-admin/',
      children: {
        Settings: {
          index: 8,
          name: 'Settings',
          children: {
            'options-general.php': {
              adminUrl: 'https://fabrikat.local/dennis/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-general.php',
              index: 0,
              name: 'General',
              nameParent: 'Settings',
              path: 'options-general.php',
              siteId: 312,
              type: 'menu',
            },
          },
        },
      },
      siteId: 312,
      type: 'menu',
    },
    {
      children: {
        '1': {
          ID: 1,
          post_author: '1',
          post_date: '2020-05-25 12:34:29',
          post_date_gmt: '2020-05-25 12:34:29',
          post_content:
            'Welcome to <a href="https://fabrikat.local/">spacepress</a>. This is your first post. Edit or delete it, then start blogging!',
          post_title: 'Hello world!',
          post_excerpt: '',
          post_status: 'publish',
          comment_status: 'open',
          ping_status: 'open',
          post_password: '',
          post_name: 'hello-world',
          to_ping: '',
          pinged: '',
          post_modified: '2020-05-25 12:34:29',
          post_modified_gmt: '2020-05-25 12:34:29',
          post_content_filtered: '',
          post_parent: 0,
          guid: 'https://fabrikat.local/harmoni/?p=1',
          menu_order: 0,
          post_type: 'post',
          post_mime_type: '',
          comment_count: '1',
          filter: 'raw',
          hrefEdit:
            'https://fabrikat.local/harmoni/wp-admin/post.php?post=1&amp;action=edit',
          name: 'Hello world!',
          siteId: 305,
        },
        '14': {
          ID: 14,
          post_author: '1',
          post_date: '2020-10-23 22:41:12',
          post_date_gmt: '2020-10-23 22:41:12',
          post_content: '',
          post_title: 'Documentation',
          post_excerpt: '',
          post_status: 'publish',
          comment_status: 'closed',
          ping_status: 'closed',
          post_password: '',
          post_name: 'documentation',
          to_ping: '',
          pinged: '',
          post_modified: '2020-10-23 22:41:12',
          post_modified_gmt: '2020-10-23 22:41:12',
          post_content_filtered: '',
          post_parent: 0,
          guid: 'https://fabrikat.local/harmoni/?page_id=14',
          menu_order: 0,
          post_type: 'page',
          post_mime_type: '',
          comment_count: '0',
          filter: 'raw',
          hrefEdit:
            'https://fabrikat.local/harmoni/wp-admin/post.php?post=14&amp;action=edit',
          name: 'Documentation',
          siteId: 305,
        },
        '22': {
          ID: 22,
          post_author: '1',
          post_date: '2021-02-16 01:11:31',
          post_date_gmt: '2021-02-16 01:11:31',
          post_content: '',
          post_title: 'Home',
          post_excerpt: '',
          post_status: 'publish',
          comment_status: 'closed',
          ping_status: 'closed',
          post_password: '',
          post_name: 'home',
          to_ping: '',
          pinged: '',
          post_modified: '2021-02-16 01:11:31',
          post_modified_gmt: '2021-02-16 01:11:31',
          post_content_filtered: '',
          post_parent: 0,
          guid: 'https://fabrikat.local/harmoni/?page_id=22',
          menu_order: 0,
          post_type: 'page',
          post_mime_type: '',
          comment_count: '0',
          filter: 'raw',
          hrefEdit:
            'https://fabrikat.local/harmoni/wp-admin/post.php?post=22&amp;action=edit',
          name: 'Home',
          siteId: 305,
        },
      },
      type: 'post',
      siteId: 305,
    },
  ];
  stateInternal.entriesFav = fav;
  stateInternal.entriesFavActive = fav;

  const menu = [
    {
      adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
      children: {
        Dashboard: {
          index: 0,
          name: 'Dashboard',
          children: {
            'index.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/index.php',
              index: 0,
              name: 'Home',
              nameParent: 'Dashboard',
              path: 'index.php',
              siteId: 305,
              type: 'menu',
            },
            'index.php?page=relevanssi/relevanssi.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/index.php?page=relevanssi/relevanssi.php',
              index: 1,
              name: 'User searches',
              nameParent: 'Dashboard',
              path: 'index.php?page=relevanssi/relevanssi.php',
              siteId: 305,
              type: 'menu',
            },
            'index.php?page=relevanssi_admin_search': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/index.php?page=relevanssi_admin_search',
              index: 2,
              name: 'Admin search',
              nameParent: 'Dashboard',
              path: 'index.php?page=relevanssi_admin_search',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Posts: {
          index: 1,
          name: 'Posts',
          children: {
            'edit.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php',
              index: 0,
              name: 'All Posts',
              nameParent: 'Posts',
              path: 'edit.php',
              siteId: 305,
              type: 'menu',
            },
            'post-new.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/post-new.php',
              index: 1,
              name: 'Add New',
              nameParent: 'Posts',
              path: 'post-new.php',
              siteId: 305,
              type: 'menu',
            },
            'edit-tags.php?taxonomy=category': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit-tags.php?taxonomy=category',
              index: 2,
              name: 'Categories',
              nameParent: 'Posts',
              path: 'edit-tags.php?taxonomy=category',
              siteId: 305,
              type: 'menu',
            },
            'edit-tags.php?taxonomy=post_tag': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit-tags.php?taxonomy=post_tag',
              index: 3,
              name: 'Tags',
              nameParent: 'Posts',
              path: 'edit-tags.php?taxonomy=post_tag',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Media: {
          index: 2,
          name: 'Media',
          children: {
            'upload.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/upload.php',
              index: 0,
              name: 'Library',
              nameParent: 'Media',
              path: 'upload.php',
              siteId: 305,
              type: 'menu',
            },
            'media-new.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/media-new.php',
              index: 1,
              name: 'Add New',
              nameParent: 'Media',
              path: 'media-new.php',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Pages: {
          index: 3,
          name: 'Pages',
          children: {
            'edit.php?post_type=page': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=page',
              index: 0,
              name: 'All Pages',
              nameParent: 'Pages',
              path: 'edit.php?post_type=page',
              siteId: 305,
              type: 'menu',
            },
            'post-new.php?post_type=page': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/post-new.php?post_type=page',
              index: 1,
              name: 'Add New',
              nameParent: 'Pages',
              path: 'post-new.php?post_type=page',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Appearance: {
          index: 4,
          name: 'Appearance',
          children: {
            'themes.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/themes.php',
              index: 0,
              name: 'Themes',
              nameParent: 'Appearance',
              path: 'themes.php',
              siteId: 305,
              type: 'menu',
            },
            'customize.php?return=%2Fharmoni%2Fwp-admin%2F': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/customize.php?return=%2Fharmoni%2Fwp-admin%2F',
              index: 1,
              name: 'Customize',
              nameParent: 'Appearance',
              path: 'customize.php?return=%2Fharmoni%2Fwp-admin%2F',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Plugins: {
          index: 5,
          name: 'Plugins',
          children: {
            'plugins.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/plugins.php',
              index: 0,
              name: 'Plugins',
              nameParent: 'Plugins',
              path: 'plugins.php',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Users: {
          index: 6,
          name: 'Users',
          children: {
            'users.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/users.php',
              index: 0,
              name: 'All Users',
              nameParent: 'Users',
              path: 'users.php',
              siteId: 305,
              type: 'menu',
            },
            'user-new.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/user-new.php',
              index: 1,
              name: 'Add New',
              nameParent: 'Users',
              path: 'user-new.php',
              siteId: 305,
              type: 'menu',
            },
            'profile.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/profile.php',
              index: 2,
              name: 'Profile',
              nameParent: 'Users',
              path: 'profile.php',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Tools: {
          index: 7,
          name: 'Tools',
          children: {
            'tools.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/tools.php',
              index: 0,
              name: 'Available Tools',
              nameParent: 'Tools',
              path: 'tools.php',
              siteId: 305,
              type: 'menu',
            },
            'import.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/import.php',
              index: 1,
              name: 'Import',
              nameParent: 'Tools',
              path: 'import.php',
              siteId: 305,
              type: 'menu',
            },
            'export.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/export.php',
              index: 2,
              name: 'Export',
              nameParent: 'Tools',
              path: 'export.php',
              siteId: 305,
              type: 'menu',
            },
            'site-health.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/site-health.php',
              index: 3,
              name: 'Site Health',
              nameParent: 'Tools',
              path: 'site-health.php',
              siteId: 305,
              type: 'menu',
            },
            'export-personal-data.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/export-personal-data.php',
              index: 4,
              name: 'Export Personal Data',
              nameParent: 'Tools',
              path: 'export-personal-data.php',
              siteId: 305,
              type: 'menu',
            },
            'erase-personal-data.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/erase-personal-data.php',
              index: 5,
              name: 'Erase Personal Data',
              nameParent: 'Tools',
              path: 'erase-personal-data.php',
              siteId: 305,
              type: 'menu',
            },
            'ms-delete-site.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/ms-delete-site.php',
              index: 6,
              name: 'Delete Site',
              nameParent: 'Tools',
              path: 'ms-delete-site.php',
              siteId: 305,
              type: 'menu',
            },
            'tools.php?page=wp-migrate-db-pro': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/tools.php?page=wp-migrate-db-pro',
              index: 7,
              name: 'Migrate DB Pro',
              nameParent: 'Tools',
              path: 'tools.php?page=wp-migrate-db-pro',
              siteId: 305,
              type: 'menu',
            },
            'tools.php?page=spx-license': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/tools.php?page=spx-license',
              index: 8,
              name: 'spx',
              nameParent: 'Tools',
              path: 'tools.php?page=spx-license',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        Settings: {
          index: 8,
          name: 'Settings',
          children: {
            'options-general.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-general.php',
              index: 0,
              name: 'General',
              nameParent: 'Settings',
              path: 'options-general.php',
              siteId: 305,
              type: 'menu',
            },
            'options-writing.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-writing.php',
              index: 1,
              name: 'Writing',
              nameParent: 'Settings',
              path: 'options-writing.php',
              siteId: 305,
              type: 'menu',
            },
            'options-reading.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-reading.php',
              index: 2,
              name: 'Reading',
              nameParent: 'Settings',
              path: 'options-reading.php',
              siteId: 305,
              type: 'menu',
            },
            'options-media.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-media.php',
              index: 3,
              name: 'Media',
              nameParent: 'Settings',
              path: 'options-media.php',
              siteId: 305,
              type: 'menu',
            },
            'options-permalink.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-permalink.php',
              index: 4,
              name: 'Permalinks',
              nameParent: 'Settings',
              path: 'options-permalink.php',
              siteId: 305,
              type: 'menu',
            },
            'options-privacy.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-privacy.php',
              index: 5,
              name: 'Privacy',
              nameParent: 'Settings',
              path: 'options-privacy.php',
              siteId: 305,
              type: 'menu',
            },
            'options-general.php?page=relevanssi/relevanssi.php': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/options-general.php?page=relevanssi/relevanssi.php',
              index: 6,
              name: 'Relevanssi',
              nameParent: 'Settings',
              path: 'options-general.php?page=relevanssi/relevanssi.php',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        'Custom Fields': {
          index: 9,
          name: 'Custom Fields',
          children: {
            'edit.php?post_type=acf-field-group': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=acf-field-group',
              index: 0,
              name: 'Field Groups',
              nameParent: 'Custom Fields',
              path: 'edit.php?post_type=acf-field-group',
              siteId: 305,
              type: 'menu',
            },
            'post-new.php?post_type=acf-field-group': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/post-new.php?post_type=acf-field-group',
              index: 1,
              name: 'Add New',
              nameParent: 'Custom Fields',
              path: 'post-new.php?post_type=acf-field-group',
              siteId: 305,
              type: 'menu',
            },
            'edit.php?post_type=acf-field-group&page=acf-tools': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=acf-field-group&page=acf-tools',
              index: 2,
              name: 'Tools',
              nameParent: 'Custom Fields',
              path: 'edit.php?post_type=acf-field-group&page=acf-tools',
              siteId: 305,
              type: 'menu',
            },
            'edit.php?post_type=acf-field-group&page=acf-settings-updates': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/edit.php?post_type=acf-field-group&page=acf-settings-updates',
              index: 3,
              name: 'Updates',
              nameParent: 'Custom Fields',
              path: 'edit.php?post_type=acf-field-group&page=acf-settings-updates',
              siteId: 305,
              type: 'menu',
            },
          },
        },
        SEO: {
          index: 10,
          name: 'SEO',
          children: {
            'admin.php?page=theseoframework-settings': {
              adminUrl: 'https://fabrikat.local/harmoni/wp-admin/',
              href: 'https://fabrikat.local/harmoni/wp-admin/admin.php?page=theseoframework-settings',
              index: 0,
              name: 'SEO',
              nameParent: 'SEO',
              path: 'admin.php?page=theseoframework-settings',
              siteId: 305,
              type: 'menu',
            },
          },
        },
      },
      siteId: 305,
      type: 'menu',
    },
  ];
  stateInternal.entriesMenu = menu;
  stateInternal.entriesMenuActive = menu;

  const post = [
    {
      title: 'Posts',
      children: {
        '1': {
          ID: 1,
          post_author: '1',
          post_date: '2020-05-25 12:34:29',
          post_date_gmt: '2020-05-25 12:34:29',
          post_content:
            'Welcome to <a href="https://fabrikat.local/">spacepress</a>. This is your first post. Edit or delete it, then start blogging!',
          post_title: 'Hello world!',
          post_excerpt: '',
          post_status: 'publish',
          comment_status: 'open',
          ping_status: 'open',
          post_password: '',
          post_name: 'hello-world',
          to_ping: '',
          pinged: '',
          post_modified: '2020-05-25 12:34:29',
          post_modified_gmt: '2020-05-25 12:34:29',
          post_content_filtered: '',
          post_parent: 0,
          guid: 'https://fabrikat.local/harmoni/?p=1',
          menu_order: 0,
          post_type: 'post',
          post_mime_type: '',
          comment_count: '1',
          filter: 'raw',
          hrefEdit:
            'https://fabrikat.local/harmoni/wp-admin/post.php?post=1&amp;action=edit',
          name: 'Hello world!',
          siteId: 305,
        },
        '14': {
          ID: 14,
          post_author: '1',
          post_date: '2020-10-23 22:41:12',
          post_date_gmt: '2020-10-23 22:41:12',
          post_content: '',
          post_title: 'Documentation',
          post_excerpt: '',
          post_status: 'publish',
          comment_status: 'closed',
          ping_status: 'closed',
          post_password: '',
          post_name: 'documentation',
          to_ping: '',
          pinged: '',
          post_modified: '2020-10-23 22:41:12',
          post_modified_gmt: '2020-10-23 22:41:12',
          post_content_filtered: '',
          post_parent: 0,
          guid: 'https://fabrikat.local/harmoni/?page_id=14',
          menu_order: 0,
          post_type: 'page',
          post_mime_type: '',
          comment_count: '0',
          filter: 'raw',
          hrefEdit:
            'https://fabrikat.local/harmoni/wp-admin/post.php?post=14&amp;action=edit',
          name: 'Documentation',
          siteId: 305,
        },
        '22': {
          ID: 22,
          post_author: '1',
          post_date: '2021-02-16 01:11:31',
          post_date_gmt: '2021-02-16 01:11:31',
          post_content: '',
          post_title: 'Home',
          post_excerpt: '',
          post_status: 'publish',
          comment_status: 'closed',
          ping_status: 'closed',
          post_password: '',
          post_name: 'home',
          to_ping: '',
          pinged: '',
          post_modified: '2021-02-16 01:11:31',
          post_modified_gmt: '2021-02-16 01:11:31',
          post_content_filtered: '',
          post_parent: 0,
          guid: 'https://fabrikat.local/harmoni/?page_id=22',
          menu_order: 0,
          post_type: 'page',
          post_mime_type: '',
          comment_count: '0',
          filter: 'raw',
          hrefEdit:
            'https://fabrikat.local/harmoni/wp-admin/post.php?post=22&amp;action=edit',
          name: 'Home',
          siteId: 305,
        },
      },
      type: 'post',
      siteId: 305,
    },
  ];
  stateInternal.entriesPost = post;
  stateInternal.entriesPostActive = post;
}
